In [10]:
import numpy as np
import pandas as pd
from sklearn                        import metrics, svm
from sklearn.linear_model           import LinearRegression
from sklearn.linear_model           import LogisticRegression
from sklearn.tree                   import DecisionTreeClassifier
from sklearn.neighbors              import KNeighborsClassifier
from sklearn.discriminant_analysis  import LinearDiscriminantAnalysis
from sklearn.naive_bayes            import GaussianNB
from sklearn.svm                    import SVC
from sklearn.model_selection        import train_test_split
from sklearn                        import preprocessing
from sklearn.metrics                import confusion_matrix, classification_report


earthquake= pd.read_csv('database.csv')

earthquake.drop(['ID'],1, inplace=True)
earthquake.drop(['Source'],1, inplace=True)
earthquake.drop(['Magnitude Source'],1, inplace=True)
earthquake.drop(['Status'],1, inplace=True)
earthquake.drop(['Type'],1, inplace=True)

earthquake=earthquake.replace(np.NaN,0)

earthquake1=earthquake
earthquake1.drop(['Date'],1, inplace=True)
earthquake1.drop(['Time'],1, inplace=True)
earthquake1.drop(['Location Source'],1, inplace=True)
earthquake1.drop(['Magnitude Type'],1, inplace=True)


X=earthquake1.drop(columns=['Horizontal Error'])
y=earthquake1['Horizontal Error']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

lab_enc = preprocessing.LabelEncoder()
y_train_encoded = lab_enc.fit_transform(y_train)

lab_enc = preprocessing.LabelEncoder()
y_test_encoded = lab_enc.fit_transform(y_test)

print("MAKSIMALNA DUBINA JE 3, A KRITERIJUM RAZDVAJANJA ENTROPIJA ")

clf = DecisionTreeClassifier(max_depth=3, criterion = 'entropy')
clf.fit(X_train, y_train_encoded)

print("DecisionTreeClassifier trening podaci predikcija")
print(clf.predict(X_train))
class_train_predicted = clf.predict(X_train)

print("DecisionTreeClassifier test podaci predikcija")
print(clf.predict(X_test))
class_test_predicted = clf.predict(X_test)

print("Preciznost treninga")
train_acc = clf.score(X_train,y_train_encoded)
print (train_acc) 

print("Preciznost testa")
test_acc = clf.score(X_test,y_test_encoded)
print(test_acc)

print("Izracunavamo matricu konfuzije za trening podatke")
train_conf = confusion_matrix(y_train_encoded, class_train_predicted)
print(train_conf)

print("Izracunavamo matricu konfuzije za test podatke")
test_conf = confusion_matrix(y_test_encoded, class_test_predicted)
print(test_conf)

print("MAKSIMALNA DUBINA JE 5, A KRITERIJUM RAZDVAJANJA ENTROPIJA")
clf = DecisionTreeClassifier(max_depth=5, criterion = 'entropy')
clf.fit(X_train, y_train_encoded)

print("DecisionTreeClassifier trening podaci predikcija")
print(clf.predict(X_train))
class_train_predicted = clf.predict(X_train)

print("DecisionTreeClassifier test podaci predikcija")
print(clf.predict(X_test))
class_test_predicted = clf.predict(X_test)

print("Preciznost treninga")
train_acc = clf.score(X_train,y_train_encoded)
print (train_acc) 

print("Preciznost testa")
test_acc = clf.score(X_test,y_test_encoded)
print(test_acc)

print("Izracunavamo matricu konfuzije za trening podatke")
train_conf = confusion_matrix(y_train_encoded, class_train_predicted)
print(train_conf)

print("Izracunavamo matricu konfuzije za test podatke")
test_conf = confusion_matrix(y_test_encoded, class_test_predicted)
print(test_conf)

print("MAKSIMALNA DUBINA JE 25, A KRITERIJUM RAZDVAJANJA ENTROPIJA")
clf = DecisionTreeClassifier(max_depth=25, criterion = 'entropy')
clf.fit(X_train, y_train_encoded)

print("DecisionTreeClassifier trening podaci predikcija")
print(clf.predict(X_train))
class_train_predicted = clf.predict(X_train)

print("DecisionTreeClassifier test podaci predikcija")
print(clf.predict(X_test))
class_test_predicted = clf.predict(X_test)

print("Preciznost treninga")
train_acc = clf.score(X_train,y_train_encoded)
print (train_acc) 

print("Preciznost testa")
test_acc = clf.score(X_test,y_test_encoded)
print(test_acc)

print("Izracunavamo matricu konfuzije za trening podatke")
train_conf = confusion_matrix(y_train_encoded, class_train_predicted)
print(train_conf)

print("Izracunavamo matricu konfuzije za test podatke")
test_conf = confusion_matrix(y_test_encoded, class_test_predicted)
print(test_conf)



MAKSIMALNA DUBINA JE 3, A KRITERIJUM RAZDVAJANJA ENTROPIJA 
DecisionTreeClassifier trening podaci predikcija
[0 0 0 ... 0 0 0]
DecisionTreeClassifier test podaci predikcija
[0 0 0 ... 0 0 0]
Preciznost treninga
0.9506113513802125
Preciznost testa
0.9519538757206919
Izracunavamo matricu konfuzije za trening podatke
[[17794     0     0 ...     0     0     2]
 [    0     0     0 ...     0     0     2]
 [    0     0     0 ...     0     0     1]
 ...
 [    1     0     0 ...     0     0     0]
 [    1     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     9]]
Izracunavamo matricu konfuzije za test podatke
[[4458    0    0 ...    0    0    1]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    1]
 ...
 [   1    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    1]
 [   0    0    0 ...    0    0    0]]
MAKSIMALNA DUBINA JE 5, A KRITERIJUM RAZDVAJANJA ENTROPIJA
DecisionTreeClassifier trening podaci predikcija
[0 0 0 ... 0 0 0]
DecisionTreeClassif